# Generated by Django 3.2.7 on 2021-10-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avtar.jpg', upload_to='profile_images'),
        ),
    ]
