# Generated by Django 3.2.7 on 2021-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='vicky.jpg', upload_to='profile_images'),
        ),
    ]
